// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"sample/ent/binaryfile"
	"sample/ent/user"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
)

// BinaryFile is the model entity for the BinaryFile schema.
type BinaryFile struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Filename holds the value of the "filename" field.
	Filename string `json:"filename,omitempty"`
	// Body holds the value of the "body" field.
	Body *[]byte `json:"body,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BinaryFileQuery when eager-loading is set.
	Edges      BinaryFileEdges `json:"edges"`
	user_owned *int
}

// BinaryFileEdges holds the relations/edges for other nodes in the graph.
type BinaryFileEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BinaryFileEdges) OwnerOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Owner == nil {
			// The edge owner was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Owner, nil
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BinaryFile) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case binaryfile.FieldBody:
			values[i] = new([]byte)
		case binaryfile.FieldID:
			values[i] = new(sql.NullInt64)
		case binaryfile.FieldFilename:
			values[i] = new(sql.NullString)
		case binaryfile.FieldCreatedAt, binaryfile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case binaryfile.ForeignKeys[0]: // user_owned
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type BinaryFile", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BinaryFile fields.
func (bf *BinaryFile) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case binaryfile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			bf.ID = int(value.Int64)
		case binaryfile.FieldFilename:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field filename", values[i])
			} else if value.Valid {
				bf.Filename = value.String
			}
		case binaryfile.FieldBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value != nil {
				bf.Body = value
			}
		case binaryfile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				bf.CreatedAt = value.Time
			}
		case binaryfile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				bf.UpdatedAt = value.Time
			}
		case binaryfile.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_owned", value)
			} else if value.Valid {
				bf.user_owned = new(int)
				*bf.user_owned = int(value.Int64)
			}
		}
	}
	return nil
}

// QueryOwner queries the "owner" edge of the BinaryFile entity.
func (bf *BinaryFile) QueryOwner() *UserQuery {
	return (&BinaryFileClient{config: bf.config}).QueryOwner(bf)
}

// Update returns a builder for updating this BinaryFile.
// Note that you need to call BinaryFile.Unwrap() before calling this method if this BinaryFile
// was returned from a transaction, and the transaction was committed or rolled back.
func (bf *BinaryFile) Update() *BinaryFileUpdateOne {
	return (&BinaryFileClient{config: bf.config}).UpdateOne(bf)
}

// Unwrap unwraps the BinaryFile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (bf *BinaryFile) Unwrap() *BinaryFile {
	tx, ok := bf.config.driver.(*txDriver)
	if !ok {
		panic("ent: BinaryFile is not a transactional entity")
	}
	bf.config.driver = tx.drv
	return bf
}

// String implements the fmt.Stringer.
func (bf *BinaryFile) String() string {
	var builder strings.Builder
	builder.WriteString("BinaryFile(")
	builder.WriteString(fmt.Sprintf("id=%v", bf.ID))
	builder.WriteString(", filename=")
	builder.WriteString(bf.Filename)
	if v := bf.Body; v != nil {
		builder.WriteString(", body=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", created_at=")
	builder.WriteString(bf.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(bf.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// BinaryFiles is a parsable slice of BinaryFile.
type BinaryFiles []*BinaryFile

func (bf BinaryFiles) config(cfg config) {
	for _i := range bf {
		bf[_i].config = cfg
	}
}
