// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"sample/ent/binaryfile"
	"sample/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// BinaryFileDelete is the builder for deleting a BinaryFile entity.
type BinaryFileDelete struct {
	config
	hooks    []Hook
	mutation *BinaryFileMutation
}

// Where appends a list predicates to the BinaryFileDelete builder.
func (bfd *BinaryFileDelete) Where(ps ...predicate.BinaryFile) *BinaryFileDelete {
	bfd.mutation.Where(ps...)
	return bfd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (bfd *BinaryFileDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bfd.hooks) == 0 {
		affected, err = bfd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BinaryFileMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bfd.mutation = mutation
			affected, err = bfd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bfd.hooks) - 1; i >= 0; i-- {
			if bfd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bfd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bfd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (bfd *BinaryFileDelete) ExecX(ctx context.Context) int {
	n, err := bfd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (bfd *BinaryFileDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: binaryfile.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: binaryfile.FieldID,
			},
		},
	}
	if ps := bfd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, bfd.driver, _spec)
}

// BinaryFileDeleteOne is the builder for deleting a single BinaryFile entity.
type BinaryFileDeleteOne struct {
	bfd *BinaryFileDelete
}

// Exec executes the deletion query.
func (bfdo *BinaryFileDeleteOne) Exec(ctx context.Context) error {
	n, err := bfdo.bfd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{binaryfile.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (bfdo *BinaryFileDeleteOne) ExecX(ctx context.Context) {
	bfdo.bfd.ExecX(ctx)
}
