// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BinaryFile is the predicate function for binaryfile builders.
type BinaryFile func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
